version: '3'

services:
  gogs:
    image: gogs/gogs
    ports:
      - "11022:22"
      - "11080:3000"
    volumes:
      - gogs-backup:/backup
      - gogs-data:/data

  drone-server:
    image: drone/drone
    depends_on:
      - gogs
    ports:
      - "11090:80"
    volumes:
      - drone-data:/data
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=${HOST}:11090
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:drone,machine:false,admin:true,token:634ac6a0e43978e80f37de439495944e
      - DRONE_GOGS_SERVER=http://${HOST}:11080
      - DRONE_RPC_SECRET=supersecretpasswordveryverydifficultsiempresijuradoporsnoopy

  drone-agent:
    image: drone/drone-runner-docker
    depends_on:
      - gogs
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=supersecretpasswordveryverydifficultsiempresijuradoporsnoopy

  drone-agent-bis:
    image: drone/drone-runner-docker
    depends_on:
      - gogs
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=supersecretpasswordveryverydifficultsiempresijuradoporsnoopy
      - DRONE_RUNNER_LABELS=disk:ssd,memory:high,cpu:fast

volumes:
  gogs-backup:
  gogs-data:
  drone-data:
